version: '3.8'
services:

  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@localhost:1521/ORCLCDB
      - SPRING_DATASOURCE_USERNAME=C##DOCKER
      - SPRING_DATASOURCE_PASSWORD=Manhtran1412  # Sử dụng biến môi trường từ file .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
